### ISSUE TITLE
Reporte de aplicación Web de realidad Aumentada

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-jaciel#2]
[Reporte aplicacion con objeto 3D.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-equipo-jaciel/files/8282146/Reporte.aplicacion.con.objeto.3D.pdf)

**Comment by 10154** [comment]
El trabajo cumple con todos los puntos de la rúbrica, obteniendo un porcentaje de 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado
